
### PEDIDO

GET http://localhost:8888/index.php/movil HTTP/1.1

###

DELETE http://localhost:8888/index.php/servicio/1 HTTP/1.1


###

POST http://localhost:8888/index.php/movil_odometro HTTP/1.1
Content-Type: application/json

{"modoBorrado": false
,"modoFecha": "2021-03-09T03:00:00.000Z"
,"modoFechaAlta": "2021-03-08T15:34:11.717Z"
,"modoId": 0
,"modoMoviId": 14
,"modoOdometro": 500
}


###

PUT http://localhost:8888/index.php/grupo HTTP/1.1

{
  "servId" : 4,
  "servPeriodo": 20,
  "servKM": 0,
  "servFecha": 0,
  
  }

