
### PEDIDO

GET http://localhost:8888/index.php/movil_bitacora HTTP/1.1

###

### MOVIL

GET http://localhost:8888/index.php/movil?patente=GWI322 HTTP/1.1

### 
GET http://localhost:8888/index.php/movil?descripcion=5741 HTTP/1.1

### 
GET http://localhost:8888/index.php/movil?dependencia=05&descripcion=1904 HTTP/1.1



DELETE http://localhost:8888/index.php/servicio/1 HTTP/1.1


###

POST http://localhost:8888/index.php/movil_bitacora HTTP/1.1
Content-Type: application/json

{"mobiBorrado": 0,
"mobiFecha": "2021-03-22T03:00:00.000Z",
"mobiFechaAlta": "2021-03-22T03:00:00.000Z",
"mobiId": 13,
"mobiIdAnterior": "",
"mobiIdSiguiente": "",
"mobiMoseId": 5,
"mobiMoviId": 1,
"mobiObservaciones": "prueba",
"mobiOdometro": 60000,
"mobiPendiente": true,
"mobiProximaFecha": "2021-04-21T15:37:19.026Z",
"mobiProximoOdometro": 72000,
"mobiServId": 1
}


###

PUT http://localhost:8888/index.php/grupo HTTP/1.1

{
  "servId" : 4,
  "servPeriodo": 20,
  "servKM": 0,
  "servFecha": 0,
  
  }

