
### PEDIDO

GET http://localhost:8888/index.php/movil HTTP/1.1

###

DELETE http://localhost:8888/index.php/servicio/1 HTTP/1.1


###

POST http://localhost:8888/index.php/movil HTTP/1.1
Content-Type: application/json

{
    "moviId" : 1,
}


###

PUT http://localhost:8888/index.php/movil HTTP/1.1

{
  "moviId" : 1,
  }

